#! /usr/bin/env sh

set -e

KEYS=$(find /etc/ssh -name 'ssh_host_*_key')
[ -z "$KEYS" ] && ssh-keygen -A >/dev/null 2>/dev/null

/usr/sbin/sshd -D &
sleep 5

echo $JAVA_HOME >&2

su - hadoop -c '
  export JAVA_HOME="/usr/lib/jvm/java-11-amazon-corretto" ;
  /opt/hadoop/sbin/start-dfs.sh ;
  cd /opt/hadoop ;
  /opt/hadoop/bin/hdfs dfs -mkdir /user ;
  /opt/hadoop/bin/hdfs dfs -mkdir /user/hadoop ;
  bin/hdfs dfs -mkdir -p input ;
  bin/hdfs dfs -put -f etc/hadoop/*.xml input ;
  bin/hadoop jar share/hadoop/mapreduce/hadoop-mapreduce-examples-3.3.4.jar grep input output "dfs[a-z.]+" ;
  bin/hdfs dfs -get output output ;
  cat output/* ;
  rm -rf output 
'

echo DONE >&2

sleep 60
