#! /usr/bin/env bash

set -e

echo "export JAVA_HOME=${JAVA_HOME}" > /home/hadoop/.bashrc
echo 'export PATH=/opt/hadoop/bin:/opt/hadoop/sbin:${PATH}' >> /home/hadoop/.bashrc

/usr/sbin/sshd

su -l hadoop -c start-hadoop
