version: "3.6"
networks:
  hadoop_network:

x-template: &template
  restart: on-failure
  networks:
    - hadoop_network
  env_file:
    - ./config
  healthcheck: &hc
    interval: 5s
    timeout: 3s
    start_period: 10s
    retries: 20
  volumes:
    - ./bin/topology:/bin/topology

services:
  namenode:
    <<: *template
    image: hadoop
    hostname: &name namenode
    container_name: *name
    entrypoint: /bin/namenode
    healthcheck:
      <<: *hc
      test: bash /bin/check-ports 9870 9000
    ports:
      - "9000:9000"
      - "9870:9870"

  resourcemanager:
    <<: *template
    image: hadoop
    hostname: &name resourcemanager
    container_name: *name
    entrypoint: /bin/resourcemanager
    healthcheck:
      <<: *hc
      test: bash /bin/check-ports 8088
    ports:
      - "8088:8088"
  
  worker-1: &dn
    <<: *template
    image: hadoop
    hostname: &name worker-1
    container_name: *name
    entrypoint: /bin/worker
    healthcheck:
      <<: *hc
      test: bash /bin/check-ports 8040 9867 18042 19864 19866
    ports:
      - "18040:8040"
      - "19867:9867"
      - "18042:18042"
      - "19864:19864"
      - "19866:19866"
    depends_on:
      namenode:
        condition: service_healthy
      resourcemanager:
        condition: service_healthy
    environment:
      X_HADOOP_DATANODE_PORT: 19866
      X_HADOOP_DATANODE_HTTP_PORT: 19864
      X_HADOOP_NODEMANAGER_WEB_PORT: 18042
  
  worker-2:
    << : *dn
    hostname: &name worker-2
    container_name: *name
    healthcheck:
      <<: *hc
      test: bash /bin/check-ports 8040 9867 28042 29864 29866
    ports:
      - "28040:8040"
      - "29867:9867"
      - "28042:28042"
      - "29864:29864"
      - "29866:29866"
    environment:
      X_HADOOP_DATANODE_PORT: 29866
      X_HADOOP_DATANODE_HTTP_PORT: 29864
      X_HADOOP_NODEMANAGER_WEB_PORT: 28042
  
  worker-3:
    << : *dn
    hostname: &name worker-3
    container_name: *name
    healthcheck:
      <<: *hc
      test: bash /bin/check-ports 8040 9867 38042 39864 39866
    ports:
      - "38040:8040"
      - "39867:9867"
      - "38042:38042"
      - "39864:39864"
      - "39866:39866"
    environment:
      X_HADOOP_DATANODE_PORT: 39866
      X_HADOOP_DATANODE_HTTP_PORT: 39864
      X_HADOOP_NODEMANAGER_WEB_PORT: 38042
