version: "3.6"
networks:
  hadoop_network:

x-template: &template
  image: neshkeev/hadoop
  restart: on-failure
  networks:
    - hadoop_network
  env_file:
    - ./config
  healthcheck: &hc
    interval: 5s
    timeout: 3s
    start_period: 10s
    retries: 20
  volumes:
    - ./bin/topology:/bin/topology

services:
  namenode:
    <<: *template
    hostname: &name namenode
    container_name: *name
    command:
      - hdfs
      - namenode
    healthcheck:
      <<: *hc
      test: bash /bin/check-ports 9870 9000
    ports:
      - "9000:9000"
      - "9870:9870"

  resourcemanager:
    <<: *template
    hostname: &name resourcemanager
    container_name: *name
    command:
      - yarn
      - resourcemanager
    healthcheck:
      <<: *hc
      test: bash /bin/check-ports 8088
    ports:
      - "8088:8088"
  
  worker-1: &dn
    <<: *template
    hostname: &name worker-1
    container_name: *name
    command:
      - bash
      - /bin/worker
    healthcheck:
      <<: *hc
      test: bash /bin/check-ports 18042 19864 19866
    ports:
      - "18042:18042"
      - "19864:19864"
    depends_on:
      namenode:
        condition: service_healthy
      resourcemanager:
        condition: service_healthy
    environment:
      DATANODE_PORT: 19866
      DATANODE_HTTP_PORT: 19864
      NODEMANAGER_WEB_PORT: 18042
    volumes:
      - ./bin/topology:/bin/topology
      - ./bin/worker:/bin/worker
  
  worker-2:
    << : *dn
    hostname: &name worker-2
    container_name: *name
    healthcheck:
      <<: *hc
      test: bash /bin/check-ports 28042 29864 29866
    ports:
      - "28042:28042"
      - "29864:29864"
    environment:
      DATANODE_PORT: 29866
      DATANODE_HTTP_PORT: 29864
      NODEMANAGER_WEB_PORT: 28042

  worker-3:
    << : *dn
    hostname: &name worker-3
    container_name: *name
    healthcheck:
      <<: *hc
      test: bash /bin/check-ports 38042 39864 39866
    ports:
      - "38042:38042"
      - "39864:39864"
    environment:
      DATANODE_PORT: 39866
      DATANODE_HTTP_PORT: 39864
      NODEMANAGER_WEB_PORT: 38042
