version: "3.6"
networks:
  hadoop_network:

x-check-ports: &check-ports ./bin/check-ports:/bin/check-ports

x-template: &template
  restart: on-failure
  networks:
    - hadoop_network
  healthcheck: &hc
    interval: 5s
    timeout: 3s
    start_period: 10s
    retries: 20

services:
  namenode:
    <<: *template
    image: neshkeev/hadoop
    hostname: &name namenode
    container_name: *name
    healthcheck:
      <<: *hc
      test: bash /bin/check-ports 9870 9000
    ports:
      - "9000:9000"
      - "9870:9870"
    volumes:
      - *check-ports
      - ./conf/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml
      - ./conf/hdfs-site.xml:/opt/hadoop/etc/hadoop/hdfs-site.xml
      - ./bin/namenode:/bin/entrypoint
      - ./bin/topology:/bin/topology

  resourcemanager:
    <<: *template
    image: neshkeev/hadoop
    hostname: &name resourcemanager
    container_name: *name
    healthcheck:
      <<: *hc
      test: bash /bin/check-ports 8088
    ports:
      - "8088:8088"
    volumes:
      - *check-ports
      - ./conf/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml
      - ./conf/hdfs-site.xml:/opt/hadoop/etc/hadoop/hdfs-site.xml
      - ./conf/yarn-site.xml:/opt/hadoop/etc/hadoop/yarn-site.xml
      - ./bin/resourcemanager:/bin/entrypoint
      - ./bin/topology:/bin/topology

  worker-1: &dn
    <<: *template
    image: neshkeev/hadoop
    hostname: &name worker-1
    container_name: *name
    healthcheck:
      <<: *hc
      test: bash /bin/check-ports 8040 9867 18042 19864 19866
    ports:
      - "18040:8040"
      - "19867:9867"
      - "18042:18042"
      - "19864:19864"
      - "19866:19866"
    volumes:
      - *check-ports
      - ./conf/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml
      - ./conf/hdfs-site.xml:/opt/hadoop/etc/hadoop/hdfs-site.xml
      - ./conf/yarn-site.xml:/opt/hadoop/etc/hadoop/yarn-site.xml
      - ./bin/worker:/bin/entrypoint
      - ./bin/topology:/bin/topology
    depends_on:
      namenode:
        condition: service_healthy
      resourcemanager:
        condition: service_healthy
    environment:
      X_HADOOP_DATANODE_PORT: 19866
      X_HADOOP_DATANODE_HTTP_PORT: 19864
      X_HADOOP_NODEMANAGER_WEB_PORT: 18042

  worker-2:
    << : *dn
    hostname: &name worker-2
    container_name: *name
    healthcheck:
      <<: *hc
      test: bash /bin/check-ports 8040 9867 28042 29864 29866
    ports:
      - "28040:8040"
      - "29867:9867"
      - "28042:28042"
      - "29864:29864"
      - "29866:29866"
    environment:
      X_HADOOP_DATANODE_PORT: 29866
      X_HADOOP_DATANODE_HTTP_PORT: 29864
      X_HADOOP_NODEMANAGER_WEB_PORT: 28042

  worker-3:
    << : *dn
    hostname: &name worker-3
    container_name: *name
    healthcheck:
      <<: *hc
      test: bash /bin/check-ports 8040 9867 38042 39864 39866
    ports:
      - "38040:8040"
      - "39867:9867"
      - "38042:38042"
      - "39864:39864"
      - "39866:39866"
    environment:
      X_HADOOP_DATANODE_PORT: 39866
      X_HADOOP_DATANODE_HTTP_PORT: 39864
      X_HADOOP_NODEMANAGER_WEB_PORT: 38042
