name: Build Docker Containers

on:
  push:
    branches: [ "master" ]
    paths:
      - 'bash-notebook/Dockerfile'
      - 'bash-notebook/conf/**'
      - '.github/workflows/bash-notebook-docker-image.yml'

jobs:
  build-bash-notebook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Bash Jupyter Notebook
        run: >
          docker buildx build bash-notebook --push
          --platform=linux/amd64,linux/arm64
          --file bash-notebook/Dockerfile
          --tag neshkeev/bash-notebook:latest
