name: Build Docker Containers

on:
  push:
    branches: [ "master" ]
    paths:
      - 'dind/Dockerfile'
      - 'dind/bin/**'

jobs:
  dind:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build Docker-In-Docker image
      run: docker build dind --file dind/Dockerfile --tag neshkeev/dind
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Push dind to Docker Hub
      run: docker push neshkeev/dind:latest
