name: Build Docker Containers

on:
  push:
    branches: [ "master" ]
    paths:
      - 'hadoop/Dockerfile'
      - 'hadoop/bin/**'

jobs:

  build-hadoop-jdk-1_8:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        hadoop-version: [ '2.10.2', '3.2.4']

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build hadoop --file hadoop/Dockerfile --tag neshkeev/hadoop:${{matrix.hadoop-version}}-jdk1.8-amazonlinux-2 --build-arg HADOOP_VERSION=${{matrix.hadoop-version}}
    - name: Add tag to the Docker image
      run: docker tag neshkeev/hadoop:${{matrix.hadoop-version}}-jdk1.8-amazonlinux-2 neshkeev/hadoop:${{matrix.hadoop-version}}
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Push full version to Docker Hub
      run: docker push neshkeev/hadoop:${{matrix.hadoop-version}}-jdk1.8-amazonlinux-2
    - name: Push short version to Docker Hub
      run: docker push neshkeev/hadoop:${{matrix.hadoop-version}}

  build-hadoop-jdk-arch-1_8-11:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        hadoop-version: ['3.3.5', '3.3.6']
        jdk-version: [ '8', '11' ]
        arch: [ 'x86_64', 'aarch64' ]

    steps:
    - uses: actions/checkout@v3
    - name: Build the Hadoop for JDK ${{matrix.jdk-version}} for a ${{matrix.jdk-arch}} Docker image
      run: >
        docker build hadoop
        --file hadoop/Dockerfile
        --tag neshkeev/hadoop:${{matrix.hadoop-version}}-jdk${{matrix.jdk-version}}-${{matrix.arch}}
        --build-arg BASE_JDK=${{matrix.jdk-version}}
        --build-arg JDK_ARCH=${{matrix.arch}}
        --build-arg HADOOP_VERSION=${{matrix.hadoop-version}}
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Push the Hadoop for JDK ${{matrix.jdk-version}} for a ${{matrix.jdk-arch}} Docker image
      run: docker push neshkeev/hadoop:${{matrix.hadoop-version}}-jdk${{matrix.jdk-version}}-${{matrix.arch}}

  build-latest-versions:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        jdk-version: [ '8', '11' ]
        arch: [ 'x86_64', 'aarch64' ]

    steps:
    - uses: actions/checkout@v3
    - name: Build the Hadoop jdk ${{matrix.jdk-version}} for a ${{matrix.arch}} Docker image
      run: >
        docker build hadoop
        --file hadoop/Dockerfile
        --tag neshkeev/hadoop:${{matrix.jdk-version}}-${{matrix.arch}}
        --build-arg BASE_JDK=${{matrix.jdk-version}}
        --build-arg JDK_ARCH=${{matrix.arch}}
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Push latest version to Docker Hub
      run: docker push neshkeev/hadoop:${{matrix.jdk-version}}-${{matrix.arch}}

  build-latest-hadoop-jdk-11:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Hadoop jdk 11 Docker image
      run: docker build hadoop --file hadoop/Dockerfile --tag neshkeev/hadoop:latest --build-arg BASE_JDK=11
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Push latest version to Docker Hub
      run: docker push neshkeev/hadoop:latest
