name: Build Docker Containers

on:
  push:
    branches: [ "master" ]
    paths:
      - 'hadoop/Dockerfile'
      - 'hadoop/bin/**'
      - '.github/workflows/hadoop-docker-image.yml'

jobs:

  build-hadoop-jdk-1_8:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        hadoop-version: [ '2.10.2', '3.2.4']
        jdk-version: [ '8', '11' ]

    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build the Hadoop ${{matrix.hadoop-version}} with jdk ${{matrix.jdk-version}} Docker image
        run: >
          docker build hadoop --push
          --file hadoop/Dockerfile
          --tag neshkeev/hadoop:${{matrix.hadoop-version}}-jdk-${{matrix.jdk-version}}
          --build-arg JDK_VERSION=${{matrix.jdk-version}}
          --build-arg HADOOP_VERSION=${{matrix.hadoop-version}}

  build-hadoop-jdk-1_8-11-arm64-amd64:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [ 'arm64', 'amd64']
        hadoop-version: ['3.3.5', '3.3.6']
        jdk-version: [ '8', '11' ]

    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build the Hadoop ${{matrix.hadoop-version}} with jdk ${{matrix.jdk-version}} for ${{matrix.arch}} Docker image
        run: >
          docker buildx build hadoop --push
          --platform linux/${{matrix.arch}}
          --file hadoop/Dockerfile
          --tag neshkeev/hadoop:${{matrix.hadoop-version}}-jdk-${{matrix.jdk-version}}-${{matrix.arch}}
          --build-arg JDK_VERSION=${{matrix.jdk-version}}
          --build-arg JDK_ARCH=${{matrix.arch}}
          --build-arg HADOOP_VERSION=${{matrix.hadoop-version}}

  build-latest-hadoop-jdk-1_8-11-arm64-amd64:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [ 'arm64', 'amd64']
        jdk-version: [ '8', '11' ]

    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Hadoop latest with jdk ${{matrix.jdk-version}} for ${{matrix.arch}} Docker image
        run: >
          docker buildx build hadoop --push
          --platform linux/${{matrix.arch}}
          --file hadoop/Dockerfile
          --tag neshkeev/hadoop:jdk-${{matrix.jdk-version}}-${{matrix.arch}}
          --build-arg JDK_VERSION=${{matrix.jdk-version}}
          --build-arg JDK_ARCH=${{matrix.arch}}

  build-latest-hadoop-arm64-amd64:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [ 'arm64', 'amd64']

    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Hadoop latest for ${{matrix.arch}} Docker image
        run: >
          docker buildx build hadoop --push
          --platform linux/${{matrix.arch}}
          --file hadoop/Dockerfile
          --tag neshkeev/hadoop:${{matrix.arch}}
          --build-arg JDK_ARCH=${{matrix.arch}}

  build-latest-hadoop:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Hadoop latest Docker image
        run: >
          docker buildx build hadoop --push
          --file hadoop/Dockerfile
          --tag neshkeev/hadoop:latest
