name: Build Docker Containers

on:
  push:
    branches: [ "master" ]
    paths:
      - 'hadoop/Dockerfile'
      - 'hadoop/bin/**'
      - '.github/workflows/hadoop-docker-image.yml'

jobs:
  build-pre-arm-hadoop-jdk-1_8-11:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        hadoop-version: [ '2.10.2', '3.2.4']
        jdk-version: [ '8', '11' ]
  
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Hadoop latest Docker image
        run: >
          docker buildx build hadoop --push
          --platform=linux/amd64
          --file hadoop/Dockerfile
          --tag neshkeev/hadoop:${{matrix.hadoop-version}}-jdk-${{matrix.jdk-version}}
          --build-arg JDK_VERSION=${{matrix.jdk-version}}
          --build-arg HADOOP_VERSION=${{matrix.hadoop-version}}

  build-hadoop-jdk-1_8-11:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        hadoop-version: ['3.3.5', '3.3.6']
        jdk-version: [ '8', '11' ]
  
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Hadoop latest Docker image
        run: >
          docker buildx build hadoop --push
          --platform=linux/amd64,linux/arm64
          --file hadoop/Dockerfile
          --tag neshkeev/hadoop:${{matrix.hadoop-version}}-jdk-${{matrix.jdk-version}}
          --build-arg JDK_VERSION=${{matrix.jdk-version}}
          --build-arg HADOOP_VERSION=${{matrix.hadoop-version}}

  build-latest-hadoop-jdk-1_8-11:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        jdk-version: [ '8', '11' ]

    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Hadoop latest Docker image
        run: >
          docker buildx build hadoop --push
          --platform=linux/amd64,linux/arm64
          --file hadoop/Dockerfile
          --tag neshkeev/hadoop:jdk-${{matrix.jdk-version}}
          --build-arg JDK_VERSION=${{matrix.jdk-version}}
  
  build-latest-hadoop:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Hadoop latest Docker image
        run: >
          docker buildx build hadoop --push
          --platform=linux/amd64,linux/arm64
          --file hadoop/Dockerfile
          --tag neshkeev/hadoop:latest
