name: Build Docker Containers

on:
  push:
    branches: [ "master" ]
    paths:
      - 'hadoop/Dockerfile'

jobs:

  build-hadoop-jdk-1_8:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        hadoop-version: ['2.10.1', '2.10.2', '3.2.3', '3.2.4']

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build hadoop --file hadoop/Dockerfile --tag neshkeev/hadoop:${{matrix.hadoop-version}}-jdk1.8-amazonlinux-2 --build-arg HADOOP_VERSION=${{matrix.hadoop-version}}
    - name: Add tag to the Docker image
      run: docker tag neshkeev/hadoop:${{matrix.hadoop-version}}-jdk1.8-amazonlinux-2 neshkeev/hadoop:${{matrix.hadoop-version}}
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Push full version to Docker Hub
      run: docker push neshkeev/hadoop:${{matrix.hadoop-version}}-jdk1.8-amazonlinux-2
    - name: Push short version to Docker Hub
      run: docker push neshkeev/hadoop:${{matrix.hadoop-version}}

  build-hadoop-jdk-11:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        hadoop-version: ['3.3.1', '3.3.2', '3.3.3', '3.3.4', '3.3.5', '3.3.6']
    
    steps:
    - uses: actions/checkout@v3
    - name: Build the Hadoop jdk 1.8 Docker image
      run: docker build hadoop --file hadoop/Dockerfile --tag neshkeev/hadoop:${{matrix.hadoop-version}}-jdk1.8-amazonlinux-2 --build-arg HADOOP_VERSION=${{matrix.hadoop-version}}
    - name: Build the Hadoop jdk 11 Docker image
      run: docker build hadoop --file hadoop/Dockerfile --tag neshkeev/hadoop:${{matrix.hadoop-version}}-jdk11-amazonlinux-2 --build-arg HADOOP_VERSION=${{matrix.hadoop-version}} --build-arg BASE_JDK=11
    - name: Add tag to the Docker image
      run: docker tag neshkeev/hadoop:${{matrix.hadoop-version}}-jdk11-amazonlinux-2 neshkeev/hadoop:${{matrix.hadoop-version}}
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Push hadoop jdk 1.8 version to Docker Hub
      run: docker push neshkeev/hadoop:${{matrix.hadoop-version}}-jdk11-amazonlinux-2
    - name: Push hadoop jdk 11 version to Docker Hub
      run: docker push neshkeev/hadoop:${{matrix.hadoop-version}}-jdk11-amazonlinux-2
    - name: Push short version to Docker Hub
      run: docker push neshkeev/hadoop:${{matrix.hadoop-version}}

  build-latest-hadoop-jdk-11:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Hadoop jdk 11 Docker image
      run: docker build hadoop --file hadoop/Dockerfile --tag neshkeev/hadoop:latest --build-arg BASE_JDK=11
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Push latest version to Docker Hub
      run: docker push neshkeev/hadoop:latest
